keys:
  - &admin_nikolai age1hph9r83xj7cjh8ydpvl9nstyk35cfe7703jf7z0waj9nzgjz3s3qa39n02
  - &server_eversince age1hna5dnsf2xcafg2cu7tlfdzstl6fmuy7efg6lh9ne50k0rn3gdvqfkxx79
  - &server_icedancer age1pv47vymzwlx78m9xh7yksdafz3ta6cmwtjmpy24ak42nwa9spatsuzw745
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_nikolai
          - *server_eversince
          - *server_icedancer
  - path_regex: secrets/eversince/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_nikolai
          - *server_eversince
  - path_regex: secrets/icedancer/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_nikolai
          - *server_icedancer
